# below configlines  need to go into this location: /config/packages/helium/controllino1.yaml
# change YOURMINERIP to your local hotspot IP adress

sensor:
  - platform: rest
    scan_interval: 120
    name: hotspot_blockchain
    resource: http://YOURMINERIP/miner-syncstatus
    json_attributes:
      - height_percentage
      - miner_height
      - helium_height
      - syncing_done
    value_template: "on"
  - platform: template
    sensors:
      hotspot_height_percentage:
        value_template: "{{state_attr('sensor.hotspot_blockchain', 'height_percentage')}}"
      hotspot_miner_height:
        value_template: "{{state_attr('sensor.hotspot_blockchain', 'miner_height')}}"
      hotspot_helium_height:
        value_template: "{{state_attr('sensor.hotspot_blockchain', 'helium_height')}}"
      hotspot_syncing_done:
        value_template: "{{state_attr('sensor.hotspot_blockchain', 'syncing_done')}}"

  - platform: rest
    scan_interval: 90
    name: hotspot_stats
    resource: http://YOURMINERIP/hotspotstats
    json_attributes:
      - diskusage
      - ramusage
      - cpuload
      - cputemp
    value_template: "on"
  - platform: template
    sensors:
      hotspot_diskusage:
        value_template: "{{state_attr('sensor.hotspot_stats', 'diskusage')}}"
      hotspot_ramusage:
        value_template: "{{state_attr('sensor.hotspot_stats', 'ramusage')}}"
        unit_of_measurement: "MB"
      hotspot_cpuload:
        value_template: "{{state_attr('sensor.hotspot_stats', 'cpuload')}}"
      hotspot_cputemp:
        value_template: "{{state_attr('sensor.hotspot_stats', 'cputemp') |round(1)}}"
        device_class: temperature
        unit_of_measurement: "°C"

switch:
  - platform: command_line
    switches:
      hotspot_reboot:
        command_off: 'curl "http://YOURMINERIP/miner-reboot"'

  - platform: command_line
    switches:
      hotspot_shutdown:
        command_off: 'curl "http://YOURMINERIP/miner-shutdown"'

  - platform: command_line
    switches:
      hotspot_instasync:
        command_off: 'curl "http://YOURMINERIP/miner-instasync"'

# optional if you want to get status of Lora LED. For this you need SSH access on your hotspot. If you don't have SSH simply remove below lines
binary_sensor:
  - platform: remote_rpi_gpio
    host: YOURMINERIP
    invert_logic: false
    ports:
      22: Lora on controllino1
