# below configlines  need to go into this location: /config/packages/helium/controllino1.yaml
# change YOURMINERIP to your local hotspot IP adress

sensor:
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('http://YOURMINERIP/miner-syncstatus').json()['height_percentage'])"
    scan_interval: 300
    name: Hotspot sync status

  - platform: command_line
    command: python3 -c "import requests; print(requests.get('http://YOURMINERIP/miner-syncstatus').json()['miner_height'])"
    scan_interval: 300
    name: Hotspot height

  - platform: rest
    scan_interval: 90
    name: hotspot_stats
    resource: http://YOURMINERIP/hotspotstats
    json_attributes:
      - diskusage
      - ramusage
      - cpuload
      - cputemp
    value_template: "on"
  - platform: template
    sensors:
      hotspot_diskusage:
        value_template: "{{state_attr('sensor.hotspot_stats', 'diskusage')}}"
      hotspot_ramusage:
        value_template: "{{state_attr('sensor.hotspot_stats', 'ramusage')}}"
        unit_of_measurement: "MB"
      hotspot_cpuload:
        value_template: "{{state_attr('sensor.hotspot_stats', 'cpuload')}}"
      hotspot_cputemp:
        value_template: "{{state_attr('sensor.hotspot_stats', 'cputemp') |round(1)}}"
        device_class: temperature
        unit_of_measurement: "°C"

switch:
  - platform: command_line
    switches:
      hotspot_reboot:
        command_off: 'curl "http://YOURMINERIP/miner-reboot"'

  - platform: command_line
    switches:
      hotspot_shutdown:
        command_off: 'curl "http://YOURMINERIP/miner-shutdown"'

  - platform: command_line
    switches:
      hotspot_instasync:
        command_off: 'curl "http://YOURMINERIP/miner-instasync"'

# optional if you want to get status of Lora LED. For this you need SSH access on your hotspot. If you don't have SSH simply remove below lines
binary_sensor:
  - platform: remote_rpi_gpio
    host: YOURMINERIP
    invert_logic: false
    ports:
      22: Lora on controllino1
